name: Hello Workflow

on:
  workflow_call:
    inputs:
      literal:
        description: 'Enter your message'
        required: true
        type: string
      variable:
        description: 'Enter your message'
        required: true
        type: string
jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Your Literal: ${{ github.event.inputs.literal }}"
          echo "=============================="
          echo "Your Variable: ${{ github.event.inputs.variable }}"
          echo "=============================="
          