name: Hello Workflow

on:
  workflow_call:
    inputs:
      message:
        description: 'Enter your message'
        required: true
        type: string
jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Your Message: ${{ inputs.message }}"
          echo "=============================="
          